server:
 port: 8280
spring:
 datasource:
  driverClassName: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/db_club
  username: root
  password: 1234
 devtools:
   livereload:
    enabled: true
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: create-drop
 thymeleaf:
  cache: false



